updated Readme , added hub screenshots and added screenshot index to percy script
Co-authored-by: Maria Quadri <mquadri@codeforamerica.org>

diff --git a/bin/percy b/bin/percy
--- a/bin/percy
+++ b/bin/percy
@@ -1,13 +1,31 @@
-#!/usr/bin/env zsh
+#!/usr/bin/env ruby
+APP_PATH = File.expand_path('../config/application', __dir__)
+require_relative '../config/environment'
 
-if [ -z "$(git status --porcelain)" ]; then
-  echo "== 📸 Take baseline images =="
-  git checkout main
-  npx percy exec -- rspec --tag screenshot
-  echo "== 📸 Take new images =="
-  git checkout -
-  npx percy exec -- rspec --tag screenshot
-else
-  echo "== 🚨 Please commit changes first =="
-  exit 1
-fi
+# path to your application root.
+APP_ROOT = File.expand_path("..", __dir__)
+
+def system!(*args)
+  system(*args) || abort("\n== Command #{args} failed ==")
+end
+
+FileUtils.chdir APP_ROOT do
+  system!({ "PERCY_TOKEN" => Rails.application.credentials.percy_token },
+    '
+      if [ -z $PERCY_TOKEN ]; then echo "== 🚨 Please download development.key to access PERCY_TOKEN =="; exit 1; fi
+
+      if [ -z "$(git status --porcelain)" ]; then
+        echo "== 📸 Take baseline images =="
+        git checkout main
+        npx percy exec -- rspec --tag screenshot
+        echo "== 📸 Take new images =="
+        git checkout -
+        npx percy exec -- rspec --tag screenshot
+      else
+       echo "== 🚨 Please commit changes first =="
+       exit 1
+      fi
+    '
+  )
+end
+
